In this Program
titanic dataset was imported using pandas 'read_csv'
'unique', 'categorical', 'rename_categories',' where', 'loc' functions were used

In [ ]:
import numpy as np
import pandas as pd

In [118]:
titanic_data = pd.read_csv(r'E:\vs code\datasets\titanic.csv')
titanic_data.head(30)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   
20                               Fynney, Mr. Joseph J    male  35.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   
22                        McGowan, Miss. Anna "Annie"  female  15.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   
24                      Palsson, Miss. Torborg Danira  female   8.0      3   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
26                            Emir, Mr. Farred Chehab    male   NaN      0   
27                     Fortune, Mr. Charles Alexander    male  19.0      3   
28                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0   
29                                Todoroff, Mr. Lalio    male   NaN      0   

    Parch            Ticket      Fare        Cabin Embarked  
0       0         A/5 21171    7.2500          NaN        S  
1       0          PC 17599   71.2833          C85        C  
2       0  STON/O2. 3101282    7.9250          NaN        S  
3       0            113803   53.1000         C123        S  
4       0            373450    8.0500          NaN        S  
5       0            330877    8.4583          NaN        Q  
6  

In [94]:
#in dataset , we selected survived Column and checked the unique values in it
uniquevalue_survived = titanic_data["Survived"].unique()
print("the unique values in 'Survived' is " ,uniquevalue_survived, sep= ' ')

uniquevalue_sex = titanic_data["Sex"].unique()
print("the unique values in 'Sex' is " ,uniquevalue_sex, sep= ' ')

# fr = ds["Fare"].unique()
# print("the unique values in 'Fare' is " ,fr, sep= ' ')


the unique values in 'Survived' is  [0 1]
the unique values in 'Sex' is  ['male' 'female']


In [95]:
newvalue_survived = pd.Categorical(titanic_data["Survived"])
renamevalue_survived = newvalue_survived.rename_categories(["dead","Survived"])
print(renamevalue_survived.describe())


            counts     freqs
categories                  
dead           549  0.616162
Survived       342  0.383838


In [96]:
uniquevalue_Pclass = titanic_data["Pclass"].unique()
print("the unique values in 'Passenger Class' is " ,uniquevalue_Pclass, sep= ' ')

newvalue_Pclass  = pd.Categorical(titanic_data["Pclass"], ordered= True)
print(newvalue_Pclass.sort_values)
renamevalue_Pclass = newvalue_Pclass.rename_categories(["Class1","Class2","Class3"])
print(renamevalue_Pclass.describe())

the unique values in 'Passenger Class' is  [3 1 2]
<bound method Categorical.sort_values of [3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1 < 2 < 3]>
            counts     freqs
categories                  
Class1         216  0.242424
Class2         184  0.206510
Class3         491  0.551066


In [97]:
titanic_data['Pclass']= renamevalue_Pclass
titanic_data.head(10)


PassengerId  Survived  Pclass  \
0            1         0  Class3   
1            2         1  Class1   
2            3         1  Class3   
3            4         1  Class1   
4            5         0  Class3   
5            6         0  Class3   
6            7         0  Class1   
7            8         0  Class3   
8            9         1  Class3   
9           10         1  Class2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [98]:
uniquevalue_cabin = titanic_data["Cabin"].unique
print(np.array(uniquevalue_cabin))

charvalue_cabin = titanic_data["Cabin"].astype(str)
print(type(charvalue_cabin))
char_1stvalue_cabin = np.array([i[0] for i in charvalue_cabin])
char_1stvalue_cabin = pd.Categorical(char_1stvalue_cabin)
char_1stvalue_cabin.describe()

<bound method Series.unique of 0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object>
<class 'pandas.core.series.Series'>


counts     freqs
categories                  
A               15  0.016835
B               47  0.052750
C               59  0.066218
D               33  0.037037
E               32  0.035915
F               13  0.014590
G                4  0.004489
T                1  0.001122
n              687  0.771044

In [99]:
titanic_data["Cabin"] = char_1stvalue_cabin
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0  Class3   
1            2         1  Class1   
2            3         1  Class3   
3            4         1  Class1   
4            5         0  Class3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     n        S  
1      0          PC 17599  71.2833     C        C  
2      0  STON/O2. 3101282   7.9250     n        S  
3      0            113803  53.1000     C        S  
4      0            373450   8.0500     n        S

In [106]:
Missing = np.where(titanic_data["Age"].isnull( )==True)
Missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [107]:
index_missing = titanic_data.loc[Missing]
index_missing

PassengerId  Survived  Pclass                                      Name  \
5              6         0  Class3                          Moran, Mr. James   
17            18         1  Class2              Williams, Mr. Charles Eugene   
19            20         1  Class3                   Masselmani, Mrs. Fatima   
26            27         0  Class3                   Emir, Mr. Farred Chehab   
28            29         1  Class3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0  Class3                          Razi, Mr. Raihed   
863          864         0  Class3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0  Class3               van Melkebeke, Mr. Philemon   
878          879         0  Class3                        Laleff, Mr. Kristo   
888          889         0  Class3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583     n        Q  
17     male  NaN      0      0      244373  13.0000     n        S  
19   female  NaN      0      0        2649   7.2250     n        C  
26     male  NaN      0      0        2631   7.2250     n        C  
28   female  NaN      0      0      330959   7.8792     n        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292     n        C  
863  female  NaN      8      2    CA. 2343  69.5500     n        S  
868    male  NaN      0      0      345777   9.5000     n        S  
878    male  NaN      0      0      349217   7.8958     n        S  
888  female  NaN      1      2  W./C. 6607  23.4500     n        S  

[177 rows x 12 columns]

In [117]:
maximum_fare = np.where(titanic_data['Fare'] == max(titanic_data['Fare']))
print(maximum_fare)

index_maximum_Fare = titanic_data.loc[maximum_fare]
index_maximum_Fare

(array([258, 679, 737], dtype=int64),)


PassengerId  Survived  Pclass                                Name  \
258          259         1  Class1                    Ward, Miss. Anna   
679          680         1  Class1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1  Class1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292     n        C  
679    male  36.0      0      1  PC 17755  512.3292     B        C  
737    male  35.0      0      0  PC 17755  512.3292     B        C

In [123]:
titanic_data['Family'] = titanic_data['SibSp'] + titanic_data['Parch']
maximum_family_members = np.where(titanic_data['Family']== max(titanic_data['Family']))
print(maximum_family_members)
people = titanic_data.loc[maximum_family_members]
people

(array([159, 180, 201, 324, 792, 846, 863], dtype=int64),)


PassengerId  Survived  Pclass                               Name     Sex  \
159          160         0       3         Sage, Master. Thomas Henry    male   
180          181         0       3       Sage, Miss. Constance Gladys  female   
201          202         0       3                Sage, Mr. Frederick    male   
324          325         0       3           Sage, Mr. George John Jr    male   
792          793         0       3            Sage, Miss. Stella Anna  female   
846          847         0       3           Sage, Mr. Douglas Bullen    male   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"  female   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked  Family  
159  NaN      8      2  CA. 2343  69.55   NaN        S      10  
180  NaN      8      2  CA. 2343  69.55   NaN        S      10  
201  NaN      8      2  CA. 2343  69.55   NaN        S      10  
324  NaN      8      2  CA. 2343  69.55   NaN        S      10  
792  NaN      8      2  CA. 2343  69.55   NaN        S      10  
846  NaN      8      2  CA. 2343  69.55   NaN        S      10  
863  NaN      8      2  CA. 2343  69.55   NaN        S      10